PYTHON = python3


MAIN = main.py


all: run


run:
	@echo "Executando o programa..."
	@$(PYTHON) $(MAIN)


clean:
	@echo "Limpando arquivos temporários..."
	@rm -rf __pycache__ *.pyc


.PHONY: all run clean